[build]
  command = "npm install && npm run build"
  functions = "functions"

  ## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/.netlify/functions/server"
  to = "https://helpful-profiterole-4772e4.netlify.app"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
